-- 补充 2026 年 9 月日期参数，保证"下月（1号-月末）"排班方式可运行
USE shift_mvp;

INSERT INTO date_parameters (store_id, work_date, week_day, day_type, is_legal_holiday, is_holiday_eve)
SELECT 1, d, DAYOFWEEK(d),
  CASE WHEN DAYOFWEEK(d) IN (1,7) THEN 'HOLIDAY' ELSE 'WORKDAY' END,
  0,
  CASE WHEN DAYOFWEEK(d) = 6 THEN 1 ELSE 0 END
FROM (
  SELECT DATE('2026-09-01') + INTERVAL seq DAY AS d
  FROM (
    SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6
    UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13
    UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
    UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27
    UNION ALL SELECT 28 UNION ALL SELECT 29
  ) x
) dates
-- 用 VALUES(col) 引用本次插入值（原 AS new + new.col 中 new 是派生表 dates 的别名，
-- 其不含 week_day 等列，属语法错误；VALUES() 为 MySQL 8.0 可移植写法）。
ON DUPLICATE KEY UPDATE
  week_day = VALUES(week_day),
  day_type = VALUES(day_type),
  is_legal_holiday = VALUES(is_legal_holiday),
  is_holiday_eve = VALUES(is_holiday_eve);
